# Generated by Django 4.0.2 on 2022-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'downloaded_files',
                'ordering': ['-date'],
            },
        ),
    ]
